# H2 configuration

server:
  port: 8081
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

externalApi:
  answers:
    name: "answers-api"
    url: "http://localhost:8082"


